# Variables
@baseurl=http://localhost:3333
# health check
# @name GetHealth
GET {{baseurl}}/health

###

#GET rooms
# @name GetRooms
GET {{baseurl}}/rooms
###

# Create room
# @name CreateRoom
POST {{baseurl}}/rooms 
Content-Type: application/json

{
  "name": "Sala de teste",
  "description":"Esta é uma sala de teste"
}
###
@roomId = {{CreateRoom.response.body.$.roomId}}
###
#Get Room Questions
# @name GetRoomQuestion
GET {{baseurl}}/rooms/{{roomId}}/questions

###
# Create questionCreateQuestion
# @name CreateQuestion
POST {{baseurl}}/rooms/6f05315b-1442-4bfa-af46-cf39d951f59e/questions 
Content-Type: application/json

{"question" : "Quem vai apresentar o trabalho?"}
 